<?php if ($this->canShow()): ?>
<?php $msg =  $this->getNoticeMessageText();  ?>
<script type="text/javascript">
//<![CDATA[
    var messagePopupClosed = false;
    function openMessagePopup() {
        var height = $('html-body').getHeight();
        $('message-popup-window-mask').setStyle({'height':height+'px'});
        toggleSelectsUnderBlock($('message-popup-window-mask'), false);
        Element.show('message-popup-window-mask');
        $('message-popup-window').addClassName('show');
    }

    function closeApiMessagePopup() {
        if($('success').value == 1){
        toggleSelectsUnderBlock($('message-popup-window-mask'), true);
        Element.hide('message-popup-window-mask');
        $('message-popup-window').removeClassName('show');
        messagePopupClosed = true;
        }else
        {
			$('advice-required-entry').show();
        }
    }

    Event.observe(window, 'load', openMessagePopup);
    Event.observe(window, 'keyup', function(evt) {
        if(messagePopupClosed) return;
        var code;
        if (evt.keyCode) code = evt.keyCode;
        else if (evt.which) code = evt.which;
        if (code == Event.KEY_ESC) {
            closeApiMessagePopup();
        }
    });

	function saveSaopApi() {
		$('save_button').disabled = true;
		if($('api_key').value.length <= 0 ){
			$('advice-required-entry').show();
			$('save_button').disabled = false;
			return;
		}
		new Ajax.Request('<?php echo $this->getUrl('edi/adminhtml_soapuser/saveSoapApi') ?>',
		{
			 method:'get',
			 parameters: {user_id: '<?php echo $msg['user_id']?>',api_key:$('api_key').value },
			 onSuccess: function(transport){
				 
			   var response = transport.responseText.evalJSON() || "no response text";
			   $('save_button_text').innerHTML = response.message;
			   $('success').value = response.success
			   $('api_key').disabled = true;
			   $('advice-required-entry').hide();	   
			   },
			 onFailure: function(){ alert('Something went wrong...') 
				 $('success').value = 1
				 $('save_button').disabled = false;
				 }
		});
	}
    
//]]>
</script>

<div id="message-popup-window-mask" style="display:none;"></div>
<div id="message-popup-window" class="message-popup" style="width:547px">
    <div class="message-popup-head">
        <a href="#" onclick="closeApiMessagePopup(); return false;" title="<?php echo $this->getCloseText(); ?>">
			<span><?php echo $this->getCloseText(); ?></span>
		</a>
        <h2><?php echo $this->getHeaderText(); ?></h2>
    </div>
    <div class="message-popup-content"  >
        <div class="message"  style="width:489px">
            <span class="message-icon message-<?php echo $this->getSeverityText();?>" style="background-image:url(<?php echo $this->getSeverityIconsUrl() ?>);"><?php echo $this->getSeverityText();?></span>
            <div class="message-text"  style="width:430px">
            <b><?php echo $this->__('Please save below information for future reference.') ?></b>
			<p></p>
            <?php echo $this->__('SOAP USERNAME') ?> :  <b><?php echo $msg['username']; ?></b><br>
            <?php if(empty($msg['api_password'])): ?> 
				<?php echo $this->__('SOAP API KEY') ?> : <input class="required-entry input-text"type="password" name="api_key" id="api_key"> 
				<input type="hidden" name="success" id="success" value="0"> 
				<button title="save" id="save_button" type="button" class="scalable task" onclick="saveSaopApi()" style="">
					<span><span><span id="save_button_text">Save</span></span></span>
				</button>
				<div class="validation-advice" id="advice-required-entry" style="display:none"><?php echo $this->__('This is a required field.') ?></div>
            <?php endif; ?>
			<p></p>
          	<b><?php echo $this->__('This information can always be retrieved by going to System-> Configuration-> Logicbroker-> EDI-> General Information.') ?></b>
          	</div>         	
        </div>
    </div>
</div>
<?php endif; ?>
